version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
  pre_build:
    commands:
      - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/u1m0w5o5
  build:
    commands:
      - echo Building Docker image...
      - docker build -t fargate .
      - echo Pushing Docker image to ECR...
      - docker tag fargate:latest public.ecr.aws/u1m0w5o5/fargate:latest
      - docker push public.ecr.aws/u1m0w5o5/fargate:latest
  post_build:
    commands:
      - echo Build completed on date
      - echo Creating image definitions file...
      - echo '[{"name":"fargate","imageUri":"public.ecr.aws/u1m0w5o5/fargate:latest","containerPort":80}]' > imagedefinitions.json

artifacts:
  files:
    - '**/*'
  secondary-artifacts:
    imagedefinitions:
      files:
        - imagedefinitions.json
